-- Deploy quizotron:user-Update to pg

BEGIN;

set client_encoding to 'utf-8';
-- -----------------------------------------------------
-- Table "role"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "role" (

"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name"	TEXT	NOT NULL UNIQUE,
"created_at"	TIMESTAMPTZ	NOT NULL DEFAULT now(),
"updated_at"	TIMESTAMPTZ

);

-- ------------------------------------------------
--Table role seedings
-- ------------------------------------------------
INSERT INTO "role" ("id", "name") VALUES 
(1, 'admin'),
(2, 'player')
;

-- -----------------------------------------------------    
-- Table "user"
-- -----------------------------------------------------
ALTER TABLE "user" 
ADD COLUMN "role_id" INTEGER REFERENCES "role"("id") DEFAULT 2 , 
ADD COLUMN "pseudo" TEXT UNIQUE;



COMMIT;
